# WhatATheme
markdown: kramdown

# URL of the Site
url: http://francespizzuo.github.io/sitefr
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Financial Regulation Conference
# Description of the Site
description: Stanford Institute for Theoretical Economics (SITE)
# URL of Image of the Site
site-image: /assets/images/meta.jpg
# Keywords of the Site
site-keywords: SITE, Stanford, Financial regulation, Amit Seru, Greg Matvos
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://rde-stanford-edu.s3.amazonaws.com/styles/full_width/s3/Conferences/Images/SC_glance_hero.jpg?itok=MxN3h0Sw

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: 
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: 
github_username:  
youtube_channel_id: 
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname:

# Name of the Author
author-name: 
# URL for the Image of the Author
author-image: 
# 60 Words About the Author
author-about: Welcome to the site of the Financial Regulation session at the Stanford Institute for Theoretical Economics (SITE) conference. Established in 2017, this session discusses the latest advances in theoretical and empirical issues related to financial regulation, defined broadly. Topics include, but are not limited to, connections of regulation for intermediaries, households and policymakers in and outside the US. The organizers are Gregor Matvos (Kellogg School of Management, Northwestern University), and Amit Seru (Stanford Graduate School of Business).
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: 

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
